"""Report Generator — Generates reports in Markdown."""

from datetime import date, timedelta

from rich.console import Console

from btc_intel.context.builder import build_context
from btc_intel.db import get_supabase

console = Console()


def generate_report(type_: str = "daily", title: str | None = None,
                    skip_if_exists: bool = False) -> str:
    """Generate a report and save it to Supabase.

    Args:
        skip_if_exists: If True, skip generation if a report of this type
                        already exists for today. Used by automated crons.
    """
    db = get_supabase()
    today = date.today()

    # Deduplication: skip if report already exists for today
    if skip_if_exists:
        existing = (
            db.table("reports")
            .select("id")
            .eq("report_type", type_)
            .eq("period_end", str(today))
            .limit(1)
            .execute()
        )
        if existing.data:
            console.print(f"  [dim]{type_.capitalize()} report already exists for {today}, skipping[/dim]")
            return ""

    generators = {
        "daily": _generate_daily,
        "weekly": _generate_weekly,
        "cycle": _generate_cycle,
    }

    if type_ not in generators:
        console.print(f"[red]Unknown report type: {type_}. Options: {', '.join(generators.keys())}[/red]")
        return ""

    report_content = generators[type_](db)
    report_title = title or f"{type_.capitalize()} Report — {today}"

    # Calculate period
    if type_ == "weekly":
        period_start = str(today - timedelta(days=7))
    else:
        period_start = str(today)
    period_end = str(today)

    # Get current cycle score for the record
    cs = db.table("cycle_score_history").select("score").order("date", desc=True).limit(1).execute()
    current_cycle_score = cs.data[0]["score"] if cs.data else None

    # Save to Supabase (matches actual table schema)
    record = {
        "report_type": type_,
        "title": report_title,
        "content": report_content,
        "period_start": period_start,
        "period_end": period_end,
        "cycle_score": current_cycle_score,
        "generated_by": "system",
    }

    try:
        db.table("reports").insert(record).execute()
        console.print(f"[green]Report '{report_title}' saved to Supabase[/green]")
    except Exception as e:
        console.print(f"[red]Error saving report: {e}[/red]")

    # Print the report
    console.print(f"\n{report_content}")
    return report_content


def _generate_daily(db) -> str:
    """Daily report."""
    context = build_context(scope="morning")

    # Add conclusions
    conclusions = (
        db.table("conclusions")
        .select("title,content,confidence,category")
        .eq("status", "active")
        .gte("date", str(date.today() - timedelta(days=1)))
        .order("created_at", desc=True)
        .limit(5)
        .execute()
    )

    report = f"# Daily Report — {date.today()}\n\n"
    report += context
    report += "\n---\n"

    if conclusions.data:
        report += "\n## Today's Conclusions\n\n"
        for c in conclusions.data:
            report += f"### {c['title']} (confidence: {c['confidence']}/10)\n"
            report += f"{c['content']}\n\n"

    report += f"\n---\n*Auto-generated by BTC Intelligence Hub — {date.today()}*\n"
    return report


def _generate_weekly(db) -> str:
    """Weekly report."""
    week_ago = str(date.today() - timedelta(days=7))

    report = f"# Weekly Report — {week_ago} to {date.today()}\n\n"

    # Summary context
    report += build_context(scope="summary")
    report += "\n---\n"

    # Price change over week
    prices = (
        db.table("btc_prices")
        .select("date,close")
        .gte("date", week_ago)
        .order("date")
        .limit(100)
        .execute()
    )
    if prices.data and len(prices.data) >= 2:
        start_price = float(prices.data[0]["close"])
        end_price = float(prices.data[-1]["close"])
        pct = (end_price - start_price) / start_price * 100
        report += f"\n## Weekly Performance\n"
        report += f"- Start: ${start_price:,.2f}\n"
        report += f"- End: ${end_price:,.2f}\n"
        report += f"- Change: {pct:+.2f}%\n"

    # Conclusions of the week
    conclusions = (
        db.table("conclusions")
        .select("title,content,confidence,category,validated_outcome")
        .gte("date", week_ago)
        .order("created_at", desc=True)
        .limit(10)
        .execute()
    )
    if conclusions.data:
        report += f"\n## Weekly Conclusions ({len(conclusions.data)})\n\n"
        for c in conclusions.data:
            outcome = f" [{c['validated_outcome']}]" if c.get("validated_outcome") else ""
            report += f"- **{c['title']}** (conf: {c['confidence']}/10){outcome}\n"

    # Alerts of the week
    alerts = (
        db.table("alerts")
        .select("title,severity,date")
        .gte("date", week_ago)
        .order("date", desc=True)
        .limit(20)
        .execute()
    )
    if alerts.data:
        report += f"\n## Weekly Alerts ({len(alerts.data)})\n\n"
        for a in alerts.data:
            report += f"- [{a['severity'].upper()}] {a['title']} ({a['date'][:10]})\n"

    report += f"\n---\n*Auto-generated by BTC Intelligence Hub — {date.today()}*\n"
    return report


def _generate_cycle(db) -> str:
    """Cycle analysis report."""
    report = f"# Cycle Analysis — {date.today()}\n\n"

    # Deep cycle analysis
    report += build_context(scope="deep", area="cycle")
    report += "\n---\n"

    # Add technical deep
    report += "\n## Technical Context\n\n"
    report += build_context(scope="deep", area="technical")
    report += "\n---\n"

    # Cycle Score history
    scores = (
        db.table("cycle_score_history")
        .select("date,score,phase")
        .order("date", desc=True)
        .limit(30)
        .execute()
    )
    if scores.data:
        report += "\n## Cycle Score History (last 30 days)\n\n"
        for s in scores.data[:10]:
            report += f"- {s['date']}: {s['score']}/100 — {s['phase']}\n"

    report += f"\n---\n*Auto-generated by BTC Intelligence Hub — {date.today()}*\n"
    return report
